# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'Welcome to my personal webpage! Here you'll find insights into my journey, hobbies, and upcoming research project for my Data Networks and Security class.'
url:                 https://mildred97.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
