# Setup
title:               Data Networks and Security
#tagline:             'Know me better'
description:         'Welcome to my personal webpage! Here you will find insights into my journey, hobbies, and research homework for my Data Networks and Security class.'
url:                 https://mildred97.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Laura Mildred
  url:               
  email:             mildred_moreno97@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
